#!/usr/bin/env bash
# generate_env.sh
# Generates a .env file with default values and a random JWT secret.
# Run once after cloning. Safe to re-run; prompts before overwriting.
#
# Arguments:
#   --force    Overwrite existing .env without prompting
#
# Returns:
#   0 on success, 1 on cancellation or error

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *)
      echo "Usage: $0 [--force]" >&2
      exit 1
      ;;
  esac
done

if [ -f "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
  echo ".env already exists at $ENV_FILE"
  read -rp "Overwrite? [y/N]: " confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 1
  fi
fi

generate_secret() {
  # Generate a 32-byte random hex string for JWT signing
  if command -v openssl &>/dev/null; then
    openssl rand -hex 32
  elif [ -f /dev/urandom ]; then
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  else
    echo "ERROR: No suitable random source found" >&2
    exit 1
  fi
}

JWT_SECRET="$(generate_secret)"

cat >"$ENV_FILE" <<ENVEOF
# ---------------------------------------------------------------
# pytest-framework environment configuration
# Generated by scripts/generate_env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ---------------------------------------------------------------

# -- Application database (SUT) ---------------------------------
APP_DB_PATH=./data/app.db

# -- Log tracker database (Framework) ---------------------------
LOG_DB_PATH=./data/logs.db

# -- JWT authentication ------------------------------------------
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY_SECONDS=3600

# -- Log tracker limits ------------------------------------------
LOG_MAX_LINE_BYTES=16384
LOG_STORAGE_CAP_MB=256

# -- Local Docker Registry ---------------------------------------
REGISTRY_PORT=5001
ENVEOF

echo ".env written to $ENV_FILE"
echo "JWT_SECRET generated ($(echo -n "$JWT_SECRET" | wc -c) hex chars)."
exit 0
